### ISSUE TITLE
Undocumented file: pipelineOptionsSchema.json

### ISSUE THREAD

**Issue by valgen** [51Degrees/pipeline-dotnet#122]
Hi there,

We've upgraded the NuGet packages on our solution as per the following screenshot:
![Packages](https://github.com/user-attachments/assets/b10cf414-481d-4655-9c15-15ed7db88bbf)

After that a new file showed up in this folder:
![json-file](https://github.com/user-attachments/assets/bbf8d16b-7546-49ad-a2f6-ab57e695c042)

Please can you tell us where this file (pipelineOptionsSchema.json) is documented?

Thank you in advance.

Val

**Comment by justadreamer** [comment]
Hi @valgen thanks for raising this question.  This schema file appears to be a part of the [51Degrees/configuration-validation](https://github.com/51Degrees/configuration-validation) repo which is a submodule of this repository.   

The README in that repo mentions that the `pipelineOptionsSchema.json` file is used in [FiftyOne.Pipeline.Web.Framework](https://github.com/51Degrees/pipeline-dotnet/blob/d74f3e7ba6554a5df93e4045b8a113676b06e5d9/Web%20Integration/FiftyOne.Pipeline.Web.Framework/Configuration/Extensions.cs#L121-L144) to validate the user's configuration file - in fact to provide more meaningful error messages if the configuration is incorrect.  

I am wondering how you encountered this file - does it appear as a build output artifact?

**Comment by valgen** [comment]
Hi @justadreamer thanks for replying. Yes the file appears in our project under the folder we mentioned before (see screenshot). Also if we publish that folder/file gets pushed live. We are not too sure we need that in the live environment (nor in the DEV one).

Can we delete it?

**Comment by justadreamer** [comment]
Hi @valgen!  Sorry for a bit of delay.  This file is needed in runtime to validate the JSON configuration in case you change it in the future.  We would recommend keeping it. 

However if you delete it - it should be handled gracefully and validation simply will not be done - at least this is how it is in the [code](https://github.com/51Degrees/pipeline-dotnet/blob/ff94c30d6eb2673be69a2b7e28024683a9fab7bf/Web%20Integration/FiftyOne.Pipeline.Web.Framework/Configuration/Extensions.cs#L121).  Please report if you have any issues upon deleting this file.

**Comment by Tracy51D** [comment]
Hi @valgen We believe this issue to now be resolved. If you have any further issues or questions please feel free to re-open this ticket.

Regards
Tracy
