### ISSUE TITLE
Change PopulateFromDictionary to support IEnumerable<KeyValuePair<string, object>>

### ISSUE THREAD

**Issue by jwrosewell** [51Degrees/pipeline-dotnet#147]
Where the source for [PopulateFromDictionary](https://github.com/51Degrees/pipeline-dotnet/blob/f1c053944c0555d17623190793613a9ba61c762f/FiftyOne.Pipeline.Core/Data/DataBase.cs#L141) is not an IDictionary<string, object> then it must be converted to one before the method can be called. Changing the parameter type will avoid needing to do this for the called.

However the method name is PopulateFromDictionary indicating that a Dictionary is needed. A new method could be added called PopulateFrom with the type removed and the prior method left in place but marked obsolete with the advice to call the new method.

**Comment by justadreamer** [comment]
Java might need a similar change - let's check the type system.
