### ISSUE TITLE
Nightly Pipeline publishes version/4.5 as a Nuget package with the version 4.4.XXX-alpha.X. This should be 4.5

### ISSUE THREAD

**Issue by Jamesr51d** [51Degrees/pipeline-dotnet#163]
# Background 

Nightly Pipeline publishes version/4.5 as a Nuget package with the version 4.4.XXX-alpha.X. This should be 4.5

# Objective

The nuget package produced by version/4.5 should have the prefix 4.5

**Comment by justadreamer** [comment]
it uses a tag.  we tagged `version/4.5` as `4.5.0-alpha.0` - the next one will be published as `4.5.0-alpha.1` - please verify tomorrow

**Comment by justadreamer** [comment]
Publishing as 4.5.0-alpha.x now, please see: https://www.nuget.org/packages/FiftyOne.Pipeline.Core/4.5.0-alpha.1
