### ISSUE TITLE
Exceptions thrown by the 51Degrees middleware are not caught

### ISSUE THREAD

**Issue by Steve51D** [51Degrees/pipeline-dotnet#3]
The [recommended approach](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-3.1) to error handling in ASP.NET Core is to make use of 

```
app.UseExceptionHandler();
```

This adds a middleware component that traps and handles exceptions.
Unfortunately, this approach does not appear to work in conjunction with the 51Degrees middleware component that is used to pass evidence from a request into the 51Degrees Pipeline API.

This issue will be investigated and hopefully resolved in a future release. If it is important to you then please let us know so we can prioritize accordingly.

**Comment by ben51degrees** [comment]
The solution to this is to call `app.UseExceptionHandler()` before calling `app.UseFiftyOne()`. The method will be commented to make this clear in an upcomming release. It seems common with ASP app extensions to be documented as needing to be added before or after something else, so this change feels the most appropriate.

**Comment by ben51degrees** [comment]
Closed with [release 4.3.0](https://github.com/51Degrees/pipeline-dotnet/releases/tag/4.3.0), with the specific commit info being 8cd5ffd76954297cc24d77aac10fd34b1caa4da5.
