### ISSUE TITLE
Object not set to an instance of an object in WebPipeline

### ISSUE THREAD

**Issue by lgiambalvo-virtualstrongbox** [51Degrees/pipeline-dotnet#4]
On line 128 an exception is thrown because the property 'ClientSideEvidenceEnabled' is set to use the private _options property which will always be null as the value is not set until line 161.

**Comment by Steve51D** [comment]
Thanks for letting us know about this @lgiambalvo-virtualstrongbox. I'll pass it to the team for fixing and testing.

**Comment by ben51degrees** [comment]
This has been solved with commit a960cee9f7a142d8a09465049af47da49e5355f8.
