### ISSUE TITLE
Support other interface implementations for HTTP clients in CloudRequestEngine.

### ISSUE THREAD

**Issue by ben51degrees** [51Degrees/pipeline-dotnet#6]
This involves changing the parameter in the `CloudRequestEngine`'s constructor from `HttpClient` to an interface.
Implementations can then be added using `HttpClient`, and other options such as `RestSharp` and `WebRequest`. 

Options for this will also be added to the `CloudRequestEngineBuilder`, as the engine's constructor should not be called directly.

**Comment by tungntpham** [comment]
There is no interface currently available for us to use to support this. Close this now as will not be supported.
