### ISSUE TITLE
Documentation is unclear on the SuppressProcessException setting

### ISSUE THREAD

**Issue by Steve51D** [51Degrees/pipeline-dotnet#8]
This setting is very important and needs to be better documented.
In particular, the default value (false) is best for development/prototyping, but it should generally be set to true for production environments in order to avoid crashing the application.

**Comment by Automation51D** [comment]
A new page has been added in the 'features' section called 'error handling'. This covers the use of the SuppressProcessException setting and will be released with the next version of the API.
