### ISSUE TITLE
Enable Per-Detection Configuration of Enable/Disable Cookies

### ISSUE THREAD

**Issue by ben51degrees** [51Degrees/pipeline-dotnet#98]
The [`JavaScriptBuilderElement`](https://github.com/51Degrees/pipeline-dotnet/blob/main/FiftyOne.Pipeline.Elements/FiftyOne.Pipeline.JavaScriptBuilderElement/FlowElement/JavaScriptBuilderElement.cs)
currently has a build option named `EnableCookies`.

This should be configurable per request, and should be disabled by default.

### Summary of Steps
- Disable cookies by default,
- Enable configuration of cookies per-detection,
- Add evidence keys for the new option,
- Document the usage of the new feature,
- Add tests for the new feature.

### Disable by Default

Setting the option to disabled by default is a simple change to the [`BUILDER_DEFAULT_ENABLE_COOKIES`](https://github.com/51Degrees/pipeline-dotnet/blob/main/FiftyOne.Pipeline.Elements/FiftyOne.Pipeline.JavaScriptBuilderElement/Constants.cs#L113) constant.

### Per-Detection Configuration

To enable configuration per request, an additional evidence key of `query.fod-js-enable-cookies` should be added, and used in the same way as the existing `query.fod-js-object-name`. Usage of the existing option can be found starting on [lines 667-673](https://github.com/51Degrees/pipeline-dotnet/blob/main/FiftyOne.Pipeline.Elements/FiftyOne.Pipeline.JavaScriptBuilderElement/FlowElement/JavaScriptBuilderElement.cs#L667-L673).

## Evidence Keys

The new evidence key `query.fod-js-enable-cookies` should be added to the evidence keys returned by the engine.

### Tests

Tests for this should be added, and include the following:
- With a source JavaScript value that sets a cookie, and default config for the `JavaScriptBuilderElement`, the generated JavaScript should not contain any JavaScript that adds cookie values,
- With a source JavaScript value that sets a cookie, and the `JavaSctiptBuilderElement` build with `EnableCookies` set to true, the generated JavaScript should contain JavaScript that adds cookie values,
- With a source JavaScript value that sets a cookie, and the `JavaScriptBuilderElement` built with `EnableCookies` set to each of the possible values, and an evidence value of `true` for the key `query.fod-js-enable-cookies`, the generated JavaScript should contain JavaScript that adds cookie values,
- With a source JavaScript value that sets a cookie, and the `JavaScriptBuilderElement` built with `EnableCookies` set to each of the possible values, and an evidence value of `false` for the key `query.fod-js-enable-cookies`, the generated JavaScript should not contain any JavaScript that adds cookie values,

### Documentation

Documentation should be added to the builder method to make it clear that it can also be configured per-detection.

The behavior of cookies, and whether or not they are written, should be thoroughly documented in the readme with the their options (pointing to external documentation where necessary).

**Comment by justadreamer** [comment]
@ben51degrees could you please also update the specification with these new details

**Comment by ben51degrees** [comment]
As part of this work, the default will not be changed. The extra configuration options will be added, but the default will remain until the next version update as it is breaking.

**Comment by ben51degrees** [comment]
Closed by #99
